version: '3.9'
services:
  tempo:
    image: grafana/tempo:2.2.2
    networks:
      - services
    command:
      - -config.expand-env=true
      - --config.file=/etc/tempo/tempo.yml
    configs:
      - source: tempo_config
        target: /etc/tempo/tempo.yml
    volumes:
      - tempo:/var/tempo
    environment:
      MINIO_USERNAME: ${MINIO_USER_SERVICE_ACCOUNT_ACCESSKEY}
      MINIO_PASSWORD: ${MINIO_USER_SERVICE_ACCOUNT_SECRETKEY}
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
          - "node.platform.os==linux"
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        prometheus.job: tempo
        prometheus.port: 3200
        prometheus.path: /metrics
    logging:
      options:
        loki-external-labels: "job=tempo"
  create-bucket:
    image: gavanlamb/minio-create-bucket:v1.0.0
    networks:
      - services
    environment:
      ADMIN_USERNAME: ${MINIO_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${MINIO_ADMIN_PASSWORD}
      DEPLOYMENT_NAME: gavanlamb
      DEPLOYMENT_URL: http://minio:3700
      DEPLOYMENT_REGION: darlinghurst
      NEW_BUCKET_NAME: tempo
      NEW_GROUP_NAME: tempo
      NEW_POLICY_PREFIX: tempo
      NEW_USER_NAME: tempo
      NEW_USER_PASSWORD: ${MINIO_USER_PASSWORD}
      NEW_USER_SERVICE_ACCOUNT_ACCESSKEY: ${MINIO_USER_SERVICE_ACCOUNT_ACCESSKEY}
      NEW_USER_SERVICE_ACCOUNT_SECRETKEY: ${MINIO_USER_SERVICE_ACCOUNT_SECRETKEY}
    deploy:
      mode: replicated
      restart_policy:
        condition: none
      placement:
        constraints:
          - "node.role==manager"
          - "node.platform.os==linux"
    logging:
      options:
        loki-external-labels: "job=tempo-create-bucket"

configs:
  tempo_config:
    file: config/tempo.yml
    name: tempo_config

volumes:
  tempo:
    name: tempo
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.50.32,rw,noatime,rsize=8192,wsize=8192,tcp"
      device: ":/share/docker/tempo"

networks:
  services:
    name: services
    external: true
