version: '3.9'
services:
  tempo:
    image: grafana/tempo:2.2.2
    networks:
      - services
    command:
      - -config.expand-env=true
      - --config.file=/etc/tempo/tempo.yml
    configs:
      - source: tempo_config
        target: /etc/tempo/tempo.yml
    volumes:
      - tempo:/var/tempo
    environment:
      MINIO_USERNAME: ${MINIO_TEMPO_USERNAME}
      MINIO_PASSWORD: ${MINIO_TEMPO_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
          - "node.platform.os==linux"
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        prometheus.job: tempo
        prometheus.port: 3200
        prometheus.path: /metrics
    logging:
      options:
        loki-external-labels: "job=tempo"

configs:
  tempo_config:
    file: config/tempo.yml
    name: tempo_config

volumes:
  tempo:
    name: tempo
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.19,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/share/docker/tempo"

networks:
  services:
    name: services
    external: true
